### PR TITLE
Added norwegian bokmål translation, and updated toki pona for lasted

### PR DESCRIPTION
**Pull request by Gresskarpai**

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Theres a huge rewrite happening, will merge after rewrite

**Comment by Nv7-GitHub** [comment]
Need to update for language rewrite

**Comment by Gresskarpai** [comment]
Updated toki pona and norwegian bokmål for  {{ . }}

**Review by Nv7-GitHub — APPROVED** [review]
Seems good!

**Pull request merged**
