### PR TITLE
Add poorly translated^2 language

### PR DESCRIPTION
**Pull request by 1000goalgaming**

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
can we just replace poorly translated with this?

**Comment by 1000goalgaming** [comment]
honestly that's a good idea

**Comment by Nv7-GitHub** [comment]
image
It's missing these translations

**Comment by 1000goalgaming** [comment]
Where would I put those translations? They're not in any of the language JSONs 💀

**Comment by Nv7-GitHub** [comment]
They're in en_us.json

**Comment by 1000goalgaming** [comment]
done

**Comment by Nv7-GitHub** [comment]
Translation removed

**Pull request closed without merging**
