### PR TITLE
Mexican Spanish support

### PR DESCRIPTION
**Pull request by Nubo318**
Feel free to change it to "Latin American Spanish" or just "Spanish" if you prefer, but keep in mind there *may* be a few differences with other varieties, even with other latin american varieties. Also note that "y" (and) changes to "e" if the next word starts with i and that "o" (or) changes to "u" if the next word starts with o, but I don't know how to do that here.

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Probably pretty out-of-date now, need to update ur fork to match mine

**Comment by Nubo318** [comment]
done

**Comment by Nv7-GitHub** [comment]
Is this up-to-date?

**Comment by Nubo318** [comment]
it now should be

**Comment by Nv7-GitHub** [comment]
Seems good!

**Pull request merged**
